pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('dev') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('qa') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('prod') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
